---
# tasks file for vce_config_cluster_drs_group
- set_fact:
    parameter: '{{ item | combine({ "hostname": inventory_hostname }) }}'
- set_fact:
    parameter: '{{ parameter | combine({ "username": vce.admin_username }) }}'
- set_fact:
    parameter: '{{ parameter | combine({ "password": vce.admin_password }) }}'
- set_fact:
    parameter: '{{ parameter | combine({ "validate_certs": false }) }}'

- name: Config Cluster DRS Group "{{ item.name }}"
  community.vmware.vmware_drs_group: "{{ parameter }}"
  delegate_to: "{{ vce.deployment.host }}"
