---
# tasks file for vce_config_resource-pool
- name: Config Resource Pool "{{ item.name }}"
  community.vmware.vmware_resource_pool:
    hostname: '{{ inventory_hostname }}'
    username: '{{ vce.admin_username }}'
    password: '{{ vce.admin_password }}'
    datacenter: '{{ item.datacenter }}'
    cluster: '{{ item.cluster }}'
    resource_pool: '{{ item.name }}'
    state: '{{ item.state }}'
    validate_certs: false
  delegate_to: "{{ vce.deployment.host }}"