---
# tasks file for vce_config_datacenter
- name: Config Datacenter "{{ item.name }}"
  community.vmware.vmware_datacenter:
    hostname: '{{ inventory_hostname }}'
    username: '{{ vce.admin_username }}'
    password: '{{ vce.admin_password }}'
    datacenter_name: '{{ item.name }}'
    state: '{{ item.state }}'
    validate_certs: false
  delegate_to: "{{ vce.deployment.host }}"