---
# tasks file for vce_config_cluster
- name: Config Cluster "{{ item.name }}"
  community.vmware.vmware_cluster:
    hostname: '{{ inventory_hostname }}'
    username: '{{ vce.admin_username }}'
    password: '{{ vce.admin_password }}'
    datacenter: '{{ item.datacenter }}'
    cluster_name: '{{ item.name }}'
    state: '{{ item.state }}'
    validate_certs: false
  delegate_to: "{{ vce.deployment.host }}"