---
# tasks file for vce_config_folder
- set_fact:
    parameter: '{{ item | combine({ "hostname": inventory_hostname }) }}'
- set_fact:
    parameter: '{{ parameter | combine({ "username": vce.admin_username }) }}'
- set_fact:
    parameter: '{{ parameter | combine({ "password": vce.admin_password }) }}'
- set_fact:
    parameter: '{{ parameter | combine({ "validate_certs": false }) }}'

- name: Config Folder "{{ item.folder_name }}"
  community.vmware.vcenter_folder: "{{ parameter }}"
  delegate_to: "{{ vce.deployment.host }}"